version: "2.1"

services:
  adguard:
    image: adguard/adguardhome:latest@sha256:f29c58a91f79387cbbbb042e140814f58e830d457d44af03d662c8df43db9dea
    network_mode: host
    privileged: true
    volumes:
      - "adguardhome_work:/opt/adguardhome/work:rw"
      - "adguardhome_conf:/opt/adguardhome/conf:rw"
    command:
      - "--no-check-update"
      - "--web-addr"
      - "0.0.0.0:80"
      - "--config"
      - "/opt/adguardhome/conf/AdGuardHome.yaml"

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: homeassistant

  # https://github.com/klutchell/balena-tailscale
  tailscale:
    build: tailscale
    image: bh.cr/klutchell_blocks/tailscale-aarch64
    network_mode: host
    restart: on-failure
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    tmpfs:
      - /tmp
      - /var/run/
    environment:
      TS_EXTRA_ARGS: --reset
      REQUIRE_AUTH_KEY: true

  netdata:
    image: netdata/netdata:latest@sha256:5cf0f4984755de45720126f0689136cfc463be976601d84dbbb7572692a48b8a
    privileged: true
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    volumes:
      - tailscale:/var/lib/tailscale

volumes:
  adguardhome_work: {}
  adguardhome_conf: {}
  netdatalib: {}
  tailscale: {}
